### ISSUE TITLE
Silence partial implementation warnings introduced in Xcode 9

### ISSUE THREAD

**Issue by ianegordon** [material-foundation/material-internationalization-ios#19]
One example:
MDFInternationalization/Sources/UIImage+MaterialRTL.m:130:18: warning: 'imageWithHorizontallyFlippedOrientation' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    return [self imageWithHorizontallyFlippedOrientation];
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by romoore** [comment]
`UISemanticContentAttribute` is also undefined as a typedef before iOS 9. MDCCatalog now has 17 warnings introduced from MDF as a result.

**Comment by ianegordon** [comment]
PR disabling the warnings landed last night:
https://github.com/material-foundation/material-internationalization-ios/pull/23

New release imminent.

**Comment by ianegordon** [comment]
Fixed by #23
