### ISSUE TITLE
Bazel improvements

### ISSUE THREAD

**Issue by jverkoey** [material-foundation/material-internationalization-ios#29]
- [ ] WORKSPACE should use `http_archive` instead of `git_repository`
- [x] Bump build_bazel_rules_apple to 0.1.0.

**Comment by ianegordon** [comment]
What is the benefit of http_archive over git_repository?

**Comment by jverkoey** [comment]
http_archive requires a checksum and is regarded as more secure.

**Comment by jverkoey** [comment]
This is done now in 2ff10388f4a61c16a856092cdfba709ddbcdd2eb
